USE Com5600G03
GO
---EN EL CASO DE QUE NO EXISTA LA BASE DE DATOS LA CREA 
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'Com5600G03')
    CREATE DATABASE Com5600G03;

--ESQUEMA CREADO PARA LO RELACIONADO CON VENTAS
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'Ven')
		EXECUTE('CREATE SCHEMA Ven');

--ESQUEMA CREADO PARA LO RELACIONADO CON LOS PRODUCTOS
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'Prod')
	EXECUTE('CREATE SCHEMA Prod');

--ESQUEMA CREADO CON LO RELACIONADO A LAS SUCURSALES 
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'Info')
		EXECUTE('CREATE SCHEMA Info');


